address: Kansas City, MO
phone: 1 816 260 5000
email: wadelhankins@gmail.com
facebook: wadehankins
theme: flatly
banner: tripart-banner2.jpg

main-menu:
  - title: Home
    permalink: ""
  - title: About
    permalink: "index.html#about"
  - title: Tri-Part
    permalink:
    sub:
    - title: Tri-Part
      permalink: "index.html#tri-part"
    - title: Spirit
      permalink: "index.html#spirit"
    - title: Soul
      permalink: "index.html#soul"
    - title: Body
      permalink: "index.html#body"
  - title: Events
    permalink: events
  - title: Donate
    permalink: donate
  - title: Contact
    permalink: contact
